### ISSUE TITLE
Directory issue, launcher???

### ISSUE THREAD

**Issue by keojimaru** [LiamKarlMitchell/AnrinchTwelveSkyLauncher#21]
![image](https://cloud.githubusercontent.com/assets/14261199/9837189/c8cc1554-5a15-11e5-8988-1f32340b0730.png)

**Comment by raydel305** [comment]
I'm having same issue can any1 give us some tips on how to fix this

**Comment by LiamKarlMitchell** [comment]
Install it to a different location not Aeria Games?
C:\Anrinch\TwelveSky

Maybe run as admin too?

Thanks for reporting.

**Comment by Cotijebeumri** [comment]
![hack tool](https://cloud.githubusercontent.com/assets/14272919/9847483/659711cc-5ad9-11e5-95cc-d05d838531bd.png)

Wut? After instal all the time shows me this

**Comment by Cotijebeumri** [comment]
![2nd](https://cloud.githubusercontent.com/assets/14272919/9847536/e4a695d2-5ad9-11e5-8a1f-4fb2eb49f1fa.png)

Or here is a 2nd screen..

**Comment by keojimaru** [comment]
Yea I got that screen as well, even after I moved it to a new folder. :/

**Comment by Cotijebeumri** [comment]
Well I can´t do anything, If I´ll don´t close that Hack Tool then I can´t click on Nostalgia, how I close a Hack Tool it close a game.. So if someone can help, then help pls o.o

**Comment by Cotijebeumri** [comment]
Hm. Someone here who can help me or answer me?? Cuz I just lose time thx to inactivity :x

**Comment by LiamKarlMitchell** [comment]
@Cotijebeumri  My apologies for sleeping and going to work.

I have a fix for this if you download the js directory from github and place it over the files it will come right.

Downloading this and putting it in your game dir will also fix the problem of the "end of central archive."
https://mega.nz/#!UMdSCZDQ!v0pnBIsMqCQkfunoCLXlCiKlrFBloJIh1BDOZSl-vvA

There are a few different problems here. Please make a new issue for unique problems.
