### ISSUE TITLE
stuck on 18-25

### ISSUE THREAD

**Issue by sotmelon** [LiamKarlMitchell/AnrinchTwelveSkyLauncher#27]
patch will not continue past 18????? WTF

and its ut of 23 not 25

**Comment by LiamKarlMitchell** [comment]
already asked as another issue.

Download the js file HTTP Something or rather and replace the one you have :)

**Comment by LiamKarlMitchell** [comment]
https://github.com/LiamKarlMitchell/AnrinchTwelveSkyLauncher/blob/master/Launcher/js/HTTPFileProgressDownload.js
